### ISSUE TITLE
使用不了

### ISSUE THREAD

**Issue by ZGarry** [zhusaidong/HolidayApi#5]
从今天2020.5.29起，服务无法使用了。
希望作者能维护~感谢!

**Comment by zhusaidong** [comment]
不好意思，原服务器到期了，准备换新的。
我先续了一个月。现在恢复了。
如果可以的话，你可以自行搭建一个。

**Comment by ZGarry** [comment]
感谢~
可以呀~我个人的确有一个腾讯云的服务器，不过我对PHP仅仅有基础了解。

前辈如果有时间的话，具体可以加QQ交流一下（QQ：1160564525）
