### ISSUE TITLE
The API can't visit anymore.

### ISSUE THREAD

**Issue by frank0123** [zhusaidong/HolidayApi#6]
What happened to this API? I can't visit it anymore. Is it had changed the site, or need charge now? I'm very like it, please tell me more details. Thank you.

**Comment by zhusaidong** [comment]
sorry, the server was expired. and a little expensive. so i donot renewal it. you can building by youself.

**Comment by frank0123** [comment]
Sorry to hear about that. Anyway, it's really a good API for holiday, simple but effective enough. Thanks a lot.
